Gebruik maken van SKU db (usage documentation followed from: https://docs.ultralytics.com/datasets/detect/sku-110k/#dataset-yaml)

In [1]:
from ultralytics import YOLO, RTDETR
from transformers import Owlv2Processor, Owlv2ForObjectDetection, MobileViTImageProcessor, MobileViTModel, AutoProcessor, AutoModelForCausalLM, CLIPProcessor, CLIPModel
import torch
from nanoowl.owl_predictor import OwlPredictor
from PIL import Image
import cv2
import sys
import types
import importlib.machinery
import os
import clip
import pandas as pd
import duckdb

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# Load a model
model1 = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Train the model
results = model1.train(data="SKU-110K.yaml", epochs=50, imgsz=416, batch=32,  workers=8, device=0, verbose=False)
# train and train6

New https://pypi.org/project/ultralytics/8.4.38 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.37  Python-3.11.9 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 8188MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=SKU-110K.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=416, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train6, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\krist\runs\detect\train6, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\nn\modules\block.py:1324: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  attn = (q.transpose(-2, -1) @ k) * self.scale
c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\nn\modules\block.py:1326: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  x = (v @ attn.transpose(-2, -1)).view(B, C, H, W) + self.pe(v.reshape(B, C, H, W))

AMP: checks passed
train: Fast image access  (ping: 0.40.2 ms, read: 724.7183.5 MB/s, size: 976.4 KB)
train: Scanning C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels... 8216 images, 0 backgrounds, 3 corrupt: 100% ━━━━━━━━━━━━ 8219/8219 359.6it/s 22.9s<0.1s
train: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\train_1797.jpg: 3 duplicate labels removed
train: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\train_4222.jpg: ignoring corrupt image/label: image file is truncated (23 bytes not processed)
train: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\train_882.jpg: ignoring corrupt image/label: image file is truncated (3 bytes not processed)
train: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\train_924.jpg: ignoring corrupt image/label: image file is truncated (10 bytes not processed)
train: New cache created: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels.cache
val: Fast image access  (ping: 3.67.0 ms, read: 446.5189.6 MB/s, size: 1182.0 KB)
val: Scanning C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels... 588 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 588/588 292.6it/s 2.0s0.1s
val: New cache created: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\krist\runs\detect\train6\labels.jpg...
Image sizes 416 train, 416 val
Using 8 dataloader workers
Logging results to C:\Users\krist\runs\detect\train6
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

       1/50      6.01G      2.293      1.624      1.117       6055        416: 100% ━━━━━━━━━━━━ 257/257 2.2s/it 9:27<0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2s/it 32.4s.7ss
                   all        588      90968      0.698      0.619       0.63      0.298

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

       2/50      10.9G      1.805     0.8379     0.9833       6618        416: 100% ━━━━━━━━━━━━ 257/257 1.1s/it 4:31<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.5s/it 24.9s.7ss
                   all        588      90968      0.762      0.666      0.704      0.355

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

       3/50      8.54G      1.738     0.8033     0.9691       5981        416: 100% ━━━━━━━━━━━━ 257/257 1.3it/s 3:22<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3s/it 32.9s.7ss
                   all        588      90968      0.783      0.695      0.717      0.378

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

       4/50      10.3G      1.713     0.7898     0.9618       6106        416: 100% ━━━━━━━━━━━━ 257/257 1.3s/it 5:26<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2s/it 32.0s.7ss
                   all        588      90968      0.793      0.698      0.728      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

       5/50      8.33G      1.676     0.7675     0.9514       5421        416: 100% ━━━━━━━━━━━━ 257/257 1.7it/s 2:30<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3s/it 33.3s.7ss
                   all        588      90968      0.812      0.695      0.743      0.395

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

       6/50      11.3G      1.652     0.7534     0.9466       6141        416: 100% ━━━━━━━━━━━━ 257/257 1.1s/it 4:33<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 29.7s.7ss
                   all        588      90968      0.811      0.705      0.737      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

       7/50      11.3G      1.629     0.7396     0.9425       6926        416: 100% ━━━━━━━━━━━━ 257/257 2.5s/it 10:44<1.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 28.5s.7ss
                   all        588      90968      0.817      0.715      0.759       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

       8/50      6.43G      1.617     0.7325      0.939       5093        416: 100% ━━━━━━━━━━━━ 257/257 2.4s/it 10:16<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 31.2s.7ss
                   all        588      90968      0.816      0.714      0.757      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

       9/50      8.72G      1.604     0.7239      0.935       6546        416: 100% ━━━━━━━━━━━━ 257/257 2.7s/it 11:34<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 30.2s.7ss
                   all        588      90968      0.835      0.737      0.779      0.429

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      10/50      6.53G      1.606     0.7226     0.9341       5616        416: 100% ━━━━━━━━━━━━ 257/257 1.4s/it 6:04<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 29.1s.7ss
                   all        588      90968      0.843      0.739      0.787      0.433

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      11/50      10.9G      1.597     0.7175     0.9321       5251        416: 100% ━━━━━━━━━━━━ 257/257 2.1it/s 2:01<0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 29.6s.7ss
                   all        588      90968      0.842      0.745       0.79      0.436

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      12/50      9.68G      1.587     0.7095     0.9286       5672        416: 100% ━━━━━━━━━━━━ 257/257 2.6s/it 11:06<2.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 29.1s.7ss
                   all        588      90968      0.846      0.752      0.793      0.439

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      13/50       9.7G      1.579     0.7028     0.9259       5916        416: 100% ━━━━━━━━━━━━ 257/257 1.3it/s 3:12<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 30.1s.7ss
                   all        588      90968      0.843      0.743      0.791       0.44

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      14/50      9.55G      1.575     0.7015     0.9267       5539        416: 100% ━━━━━━━━━━━━ 257/257 1.1s/it 4:52<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.8s/it 28.3s.7ss
                   all        588      90968      0.851      0.752      0.795      0.446

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      15/50      8.76G      1.563     0.6987     0.9254       5520        416: 100% ━━━━━━━━━━━━ 257/257 2.8it/s 1:32<0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 30.0s.7ss
                   all        588      90968      0.846      0.749      0.799      0.446

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      16/50      5.76G      1.561      0.694     0.9239       6028        416: 100% ━━━━━━━━━━━━ 257/257 1.6s/it 7:04<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.4s/it 33.7s.7ss
                   all        588      90968      0.845      0.751        0.8      0.446

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      17/50      10.8G      1.556     0.6915     0.9229       5647        416: 100% ━━━━━━━━━━━━ 257/257 1.7it/s 2:30<0.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 28.7s.7ss
                   all        588      90968      0.853      0.753      0.803      0.451

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      18/50      9.48G      1.551     0.6884      0.922       5291        416: 100% ━━━━━━━━━━━━ 257/257 1.7it/s 2:32<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2s/it 31.9s.7ss
                   all        588      90968      0.851      0.759       0.81      0.453

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      19/50      5.79G      1.547     0.6829     0.9196       5845        416: 100% ━━━━━━━━━━━━ 257/257 1.4it/s 3:07<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 31.4s.7ss
                   all        588      90968      0.854      0.761      0.813      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      20/50       8.5G      1.539     0.6803     0.9191       5905        416: 100% ━━━━━━━━━━━━ 257/257 1.3s/it 5:40<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 30.5s.7ss
                   all        588      90968      0.855      0.766      0.812      0.456

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      21/50      6.47G      1.537     0.6772     0.9179       6292        416: 100% ━━━━━━━━━━━━ 257/257 1.6s/it 6:49<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2s/it 32.3s.7ss
                   all        588      90968       0.86      0.759      0.812      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      22/50      9.12G      1.532      0.675     0.9162       5331        416: 100% ━━━━━━━━━━━━ 257/257 1.3it/s 3:17<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 30.4s.7ss
                   all        588      90968      0.862      0.766      0.815      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      23/50      8.36G      1.535     0.6754     0.9174       6313        416: 100% ━━━━━━━━━━━━ 257/257 2.7it/s 1:37<0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 30.5s.7ss
                   all        588      90968       0.86      0.772      0.818      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      24/50      6.33G      1.535     0.6725     0.9135       6946        416: 100% ━━━━━━━━━━━━ 257/257 1.5s/it 6:15<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3s/it 32.8s.7ss
                   all        588      90968      0.865      0.773      0.817      0.465

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      25/50      6.03G      1.525     0.6678     0.9138       6005        416: 100% ━━━━━━━━━━━━ 257/257 1.8it/s 2:27<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 30.8s.7ss
                   all        588      90968      0.865      0.773      0.821      0.468

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      26/50      10.7G      1.521     0.6653     0.9123       5875        416: 100% ━━━━━━━━━━━━ 257/257 1.6s/it 6:51<3.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 28.7s.7ss
                   all        588      90968      0.868      0.768      0.818      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      27/50      6.03G       1.52     0.6645     0.9132       6307        416: 100% ━━━━━━━━━━━━ 257/257 2.1it/s 2:02<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3s/it 32.7s.7ss
                   all        588      90968      0.868      0.769       0.82      0.469

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      28/50      10.9G      1.517     0.6629     0.9116       5643        416: 100% ━━━━━━━━━━━━ 257/257 3.1s/it 13:08<2.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 29.9s.7ss
                   all        588      90968      0.867      0.782      0.822      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      29/50      8.02G      1.507     0.6582     0.9121       7112        416: 100% ━━━━━━━━━━━━ 257/257 1.7it/s 2:35<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2s/it 31.6s.7ss
                   all        588      90968      0.867      0.776      0.821      0.469

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      30/50      6.22G      1.507     0.6568     0.9093       6111        416: 100% ━━━━━━━━━━━━ 257/257 1.0s/it 4:22<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 31.3s.7ss
                   all        588      90968      0.869      0.781      0.829      0.472

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      31/50      8.57G      1.507     0.6564     0.9094       5364        416: 100% ━━━━━━━━━━━━ 257/257 1.7it/s 2:36<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 31.5s.7ss
                   all        588      90968      0.872       0.78      0.824      0.474

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      32/50      6.18G      1.503     0.6535     0.9096       5651        416: 100% ━━━━━━━━━━━━ 257/257 1.1s/it 4:45<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 29.6s.7ss
                   all        588      90968      0.871      0.779      0.824      0.473

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      33/50      9.29G      1.497     0.6499     0.9083       5296        416: 100% ━━━━━━━━━━━━ 257/257 1.0it/s 4:15<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 29.7s.7ss
                   all        588      90968      0.873       0.78      0.831      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      34/50      10.4G      1.499      0.649     0.9066       5683        416: 100% ━━━━━━━━━━━━ 257/257 2.5s/it 10:47<1.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 30.1s.7ss
                   all        588      90968      0.873      0.784      0.831      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      35/50      10.5G      1.497     0.6484     0.9067       5430        416: 100% ━━━━━━━━━━━━ 257/257 4.7s/it 20:16<1.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 28.7s.7ss
                   all        588      90968      0.873      0.785      0.833      0.479

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      36/50      5.77G      1.492     0.6455     0.9057       7276        416: 100% ━━━━━━━━━━━━ 257/257 1.1it/s 3:48<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 31.1s.7ss
                   all        588      90968      0.872      0.783      0.832      0.479

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      37/50      7.96G      1.494      0.646     0.9063       5901        416: 100% ━━━━━━━━━━━━ 257/257 3.0it/s 1:25<0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 30.7s.7ss
                   all        588      90968      0.874      0.786      0.834      0.479

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      38/50      9.12G      1.493     0.6428     0.9047       6246        416: 100% ━━━━━━━━━━━━ 257/257 1.6it/s 2:41<0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 29.4s.7ss
                   all        588      90968      0.875      0.786      0.834       0.48

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      39/50      9.58G      1.481     0.6389     0.9039       6276        416: 100% ━━━━━━━━━━━━ 257/257 1.6s/it 6:45<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.8s/it 28.0s.7ss
                   all        588      90968      0.876      0.788      0.835       0.48

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      40/50      6.94G      1.486     0.6416     0.9051       6082        416: 100% ━━━━━━━━━━━━ 257/257 2.1it/s 2:05<0.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.0s/it 29.8s.7ss
                   all        588      90968      0.877      0.788      0.835      0.481
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      41/50      6.05G      1.436     0.6334     0.9187       3139        416: 100% ━━━━━━━━━━━━ 257/257 3.7it/s 1:09<0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2s/it 31.9s.7ss
                   all        588      90968      0.871      0.788      0.833       0.48

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      42/50      6.38G      1.428     0.6256     0.9154       3252        416: 100% ━━━━━━━━━━━━ 257/257 3.9it/s 1:06<0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 28.8s.7ss
                   all        588      90968      0.876      0.787      0.833      0.481

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      43/50      5.11G      1.426     0.6217     0.9147       3942        416: 100% ━━━━━━━━━━━━ 257/257 4.0it/s 1:04<0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 29.3s.7ss
                   all        588      90968      0.875      0.788      0.835      0.481

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      44/50      6.04G      1.423     0.6193      0.914       3959        416: 100% ━━━━━━━━━━━━ 257/257 4.0it/s 1:04<0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.8s/it 27.9s.7ss
                   all        588      90968      0.878      0.786      0.835      0.482

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      45/50      8.56G      1.418     0.6164     0.9121       3485        416: 100% ━━━━━━━━━━━━ 257/257 3.6it/s 1:11<0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 29.0s.7ss
                   all        588      90968      0.875       0.79      0.835      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      46/50      5.01G      1.418     0.6155     0.9129       3155        416: 100% ━━━━━━━━━━━━ 257/257 3.9it/s 1:06<0.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.9s/it 28.7s.7ss
                   all        588      90968      0.875      0.792      0.837      0.485

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      47/50      7.12G      1.413     0.6117     0.9115       3444        416: 100% ━━━━━━━━━━━━ 257/257 3.9it/s 1:06<0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.8s/it 28.2s.7ss
                   all        588      90968      0.878      0.788      0.835      0.483

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      48/50      7.09G       1.41     0.6103     0.9113       3557        416: 100% ━━━━━━━━━━━━ 257/257 4.1it/s 1:03<0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2s/it 32.3s.7ss
                   all        588      90968      0.878       0.79      0.836      0.485

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      49/50       6.7G      1.408     0.6083     0.9105       3545        416: 100% ━━━━━━━━━━━━ 257/257 3.9it/s 1:05<0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.1s/it 30.7s.7ss
                   all        588      90968      0.879       0.79      0.837      0.485

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\ultralytics\utils\loss.py:390: UserWarning: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:217.)
  pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))

      50/50      9.18G      1.406     0.6076     0.9095       3746        416: 100% ━━━━━━━━━━━━ 257/257 3.0it/s 1:26<0.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.8s/it 28.1s.7ss
                   all        588      90968      0.878       0.79      0.836      0.485

50 epochs completed in 4.339 hours.
Optimizer stripped from C:\Users\krist\runs\detect\train6\weights\last.pt, 6.2MB
Optimizer stripped from C:\Users\krist\runs\detect\train6\weights\best.pt, 6.2MB

Validating C:\Users\krist\runs\detect\train6\weights\best.pt...
Ultralytics 8.4.37  Python-3.11.9 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 8188MiB)
Model summary (fused): 73 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 1.8s/it 17.8s.1ss
                   all        588      90968      0.878       0.79      0.836      0.485
Speed: 0.3ms preprocess, 2.6ms inference, 0.0ms loss, 14.7ms postprocess per image
Results saved to C:\Users\krist\runs\detect\train6

In [2]:
model2 = YOLO("yolo11s.pt")
results = model2.train(data="SKU-110K.yaml", epochs=50, imgsz=416, batch=16,  workers=4, device=0, verbose=False, name="yolo11s_SKU110K")

Ultralytics 8.4.37  Python-3.11.9 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 8188MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=SKU-110K.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=416, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11s_SKU110K5, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\krist\runs\detect\yolo11s_SKU110K5, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    819795  ultralytics.nn.modules.head.Detect           [1, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,428,179 parameters, 9,428,163 gradients, 21.5 GFLOPs

Transferred 493/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.30.1 ms, read: 726.6232.5 MB/s, size: 976.4 KB)
train: Scanning C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels... 8216 images, 0 backgrounds, 3 corrupt: 100% ━━━━━━━━━━━━ 8219/8219 392.4it/s 20.9s<0.1s
train: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\train_1797.jpg: 3 duplicate labels removed
train: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\train_4222.jpg: ignoring corrupt image/label: image file is truncated (23 bytes not processed)
train: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\train_882.jpg: ignoring corrupt image/label: image file is truncated (3 bytes not processed)
train: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\train_924.jpg: ignoring corrupt image/label: image file is truncated (10 bytes not processed)
train: New cache created: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels.cache
val: Fast image access  (ping: 0.40.1 ms, read: 454.9170.4 MB/s, size: 1182.0 KB)
val: Scanning C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels... 588 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 588/588 281.8it/s 2.1s<0.0s
val: New cache created: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to C:\Users\krist\runs\detect\yolo11s_SKU110K5\labels.jpg...
Image sizes 416 train, 416 val
Using 4 dataloader workers
Logging results to C:\Users\krist\runs\detect\yolo11s_SKU110K5
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50       4.8G      1.876     0.8765      1.059       2095        416: 100% ━━━━━━━━━━━━ 514/514 3.5it/s 2:25<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.4it/s 7.9s0.4s
                   all        588      90968      0.808      0.712      0.744      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      6.35G      1.661     0.7586     0.9664       2363        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:12<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.814      0.716      0.747      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      7.76G      1.627     0.7388     0.9492       1681        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:16<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.836      0.744      0.787      0.434

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      7.41G      1.582     0.7174      0.939       1745        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.841      0.748      0.786       0.43

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50      6.86G      1.563     0.7046     0.9309       1684        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:15<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 6.9s0.4s
                   all        588      90968      0.849      0.758      0.806      0.449

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50      5.16G      1.538     0.6903      0.926       2215        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.853      0.771      0.809      0.454

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50      5.83G      1.535     0.6836     0.9212       2724        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.849      0.765       0.81      0.456

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50      9.55G      1.518     0.6747     0.9197       2047        416: 100% ━━━━━━━━━━━━ 514/514 2.6it/s 3:17<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968       0.87      0.776      0.819      0.474

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50      6.94G      1.504     0.6675     0.9154       2578        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.1s0.4s
                   all        588      90968      0.872       0.78      0.826      0.475

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50      7.01G      1.492      0.659     0.9149       1905        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.871      0.787      0.832      0.479

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50       5.8G      1.487     0.6547     0.9107       1304        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.875      0.793      0.834      0.485

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      6.77G      1.486     0.6515     0.9099       3222        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.875      0.791       0.84      0.488

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      6.69G      1.473     0.6457     0.9065       1966        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.8it/s 6.9s0.4s
                   all        588      90968       0.88      0.793      0.843      0.488

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      7.14G      1.471     0.6426      0.905       2393        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.881      0.796      0.842       0.49

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50       8.9G       1.47      0.643      0.906       1527        416: 100% ━━━━━━━━━━━━ 514/514 1.8it/s 4:44<0.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.3it/s 8.1s0.4s
                   all        588      90968      0.885      0.797      0.846      0.491

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      7.19G      1.461     0.6361     0.9022       2228        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:12<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.883      0.799      0.836      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      5.29G      1.461     0.6344      0.902       2091        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:12<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.1s0.4s
                   all        588      90968      0.879      0.797      0.843      0.492

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      7.28G      1.461     0.6337     0.9011       1629        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.885      0.801      0.844      0.495

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      5.23G      1.448     0.6273     0.8994       1860        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 6.9s0.4s
                   all        588      90968       0.88      0.803      0.846      0.498

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      5.83G      1.446     0.6259     0.8994       1884        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.888      0.794      0.846      0.499

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      5.42G      1.442     0.6232     0.8983       2065        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 6.9s0.4s
                   all        588      90968      0.888      0.808       0.85      0.504

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      4.48G      1.438     0.6213     0.8974       1307        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:13<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.881       0.81      0.854      0.503

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      9.22G      1.436     0.6201     0.8979       2481        416: 100% ━━━━━━━━━━━━ 514/514 3.3it/s 2:34<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.889      0.808      0.854      0.505

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      5.87G      1.436     0.6174     0.8953       1544        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.8it/s 6.9s0.4s
                   all        588      90968      0.889      0.811      0.856      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      5.17G      1.433     0.6158     0.8958       2282        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 6.9s0.4s
                   all        588      90968      0.889      0.807      0.856      0.505

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      6.79G       1.43     0.6134     0.8941       2023        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:15<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.889      0.813      0.856      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      6.68G      1.428     0.6132     0.8946       2520        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.894      0.813      0.859      0.509

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      4.05G      1.419     0.6095     0.8927       1877        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.895      0.812      0.859       0.51

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50      6.64G      1.422     0.6088     0.8932       2113        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 6.9s0.4s
                   all        588      90968      0.894      0.814       0.86       0.51

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      5.26G       1.42     0.6064     0.8918       1442        416: 100% ━━━━━━━━━━━━ 514/514 3.9it/s 2:12<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.7it/s 7.0s0.4s
                   all        588      90968      0.894      0.816       0.86      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      7.78G      1.416     0.6031       0.89       1942        416: 100% ━━━━━━━━━━━━ 514/514 3.8it/s 2:14<0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 2.8it/s 6.8s0.4s
                   all        588      90968      0.894      0.816      0.861      0.513


In [5]:
%pip install git+https://github.com/NVIDIA-AI-IOT/nanoowl

Collecting git+https://github.com/NVIDIA-AI-IOT/nanoowl
  Cloning https://github.com/NVIDIA-AI-IOT/nanoowl to C:\Users\krist\AppData\Local\Temp\pip-req-build-4xyvhzbo
  Resolved https://github.com/NVIDIA-AI-IOT/nanoowl to commit fb553dee4c58f8c53ec2bf01f355a54648e67dbd
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: nanoowl
  Building wheel for nanoowl (pyproject.toml): started
  Building wheel for nanoowl (pyproject.toml): finished with status 'done'
  Created wheel for nanoowl: filename=nanoowl-0.0.0-py3-none-any.whl size=27414 sha256=65faee752961e1892728c467950570d7f1ebae379bfc45596c12ad79416ddf28
  Stored in directory: C:\Users\krist\AppData\Local\Temp\pip-ephem-wheel-cache-8xks3uvs\wheels\89\06\45\ecb771209ce4efebeb548676c3c3674c27fb633400d5a7787c
Successfully built nanoowl
Installing collected packages: nanoowl
Successfully installed nanoowl-0.0.0
Note: you may need to restart the kernel to use updated packages.

  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA-AI-IOT/nanoowl 'C:\Users\krist\AppData\Local\Temp\pip-req-build-4xyvhzbo'

In [3]:
# Use the best model
model1 = YOLO(r'C:\Users\krist\runs\detect\train\weights\best.pt')
model2 = YOLO(r'C:\Users\krist\runs\detect\yolo11s_SKU110K5\weights\best.pt')

In [6]:
model1.val(data="SKU-110K.yaml", split="test")
model2.val(data="SKU-110K.yaml", split="test")

Ultralytics 8.4.37  Python-3.11.9 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 8188MiB)
Model summary (fused): 73 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access  (ping: 0.30.1 ms, read: 79.914.2 MB/s, size: 1014.0 KB)
val: Scanning C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels... 2935 images, 0 backgrounds, 1 corrupt: 100% ━━━━━━━━━━━━ 2936/2936 214.1it/s 13.7s0.1s
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1029.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1035.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1059.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1086.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1090.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1102.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_112.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1121.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1124.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1168.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1213.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_123.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1233.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1249.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_125.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1286.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1320.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1343.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1367.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1370.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1382.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_14.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1424.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1430.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1445.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1453.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1459.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_146.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1488.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1493.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1509.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1512.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1516.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1517.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_153.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1536.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1545.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1559.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1569.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1605.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1614.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1619.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1623.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_164.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1659.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1662.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1666.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1680.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1707.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1726.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1731.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1744.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1768.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1793.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1799.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_180.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1801.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1806.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1818.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1830.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1882.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1892.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_191.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1913.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1933.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1935.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1939.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1942.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1945.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1947.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1961.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1970.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1973.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1984.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2004.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2006.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2032.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2044.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2048.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_206.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2082.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2086.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2091.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2095.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2117.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2127.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2148.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2157.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2164.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2167.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2207.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2210.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2213.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2233.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2247.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2281.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2316.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2358.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2372.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2375.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2383.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_246.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2469.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_2475.jpg: corrupt JPEG restored and saved

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000025389405090>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,     0.99746,     0.99746,     0.99746,     0.99744,     0.99579,     0.99579,     0.99579,     0.99579,     0.99579,     0.99579,     0.99579,     0.99579,     0.99579,     0.99579,     0.99579,     0.99579,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,
            0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99577,     0.99564,      0.9956,     0.99559,     0.99551,
            0.99551,     0.99551,     0.99549,     0.99549,     0.99549,     0.99549,     0.99549,     0.99549,     0.99539,     0.99532,     0.99531,     0.99524,     0.99524,     0.99524,     0.99524,     0.99524,     0.99524,     0.99524,     0.99524,     0.99524,     0.99524,     0.99524,     0.99524,
            0.99515,     0.99512,     0.99512,     0.99512,     0.99509,     0.99503,     0.99499,     0.99486,     0.99479,     0.99479,     0.99477,     0.99477,     0.99477,     0.99477,     0.99477,     0.99477,     0.99477,     0.99477,     0.99477,     0.99477,     0.99477,     0.99477,     0.99477,
            0.99475,     0.99472,     0.99471,     0.99471,     0.99471,     0.99469,     0.99469,     0.99469,     0.99469,     0.99469,     0.99469,     0.99469,     0.99469,     0.99467,     0.99462,     0.99458,     0.99457,     0.99454,     0.99453,     0.99453,     0.99452,     0.99452,     0.99451,
            0.99451,     0.99448,     0.99448,     0.99448,     0.99448,     0.99442,     0.99439,     0.99438,     0.99433,      0.9943,     0.99429,     0.99429,     0.99429,     0.99427,     0.99427,     0.99427,     0.99427,     0.99427,     0.99427,     0.99426,     0.99424,     0.99423,     0.99422,
            0.99421,     0.99421,     0.99419,     0.99414,     0.99414,     0.99414,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,     0.99412,
            0.99412,     0.99412,     0.99412,     0.99412,     0.99412,      0.9941,     0.99404,     0.99404,     0.99404,     0.99404,     0.99403,     0.99403,     0.99396,     0.99396,     0.99393,     0.99393,     0.99393,     0.99393,     0.99393,     0.99393,     0.99391,     0.99391,     0.99391,
            0.99389,     0.99388,     0.99385,     0.99382,     0.99378,     0.99373,      0.9937,     0.99366,     0.99358,     0.99358,     0.99358,     0.99355,     0.99353,     0.99344,     0.99341,     0.99341,     0.99341,     0.99341,      0.9934,     0.99339,     0.99339,     0.99338,     0.99336,
            0.99336,     0.99332,     0.99332,     0.99331,      0.9933,     0.99329,     0.99327,     0.99326,     0.99326,     0.99326,     0.99323,     0.99323,     0.99322,     0.99319,     0.99319,     0.99316,     0.99316,     0.99316,     0.99316,     0.99316,     0.99316,     0.99315,     0.99315,
            0.99313,      0.9931,     0.99309,     0.99309,     0.99307,     0.99307,     0.99307,     0.99307,     0.99307,     0.99307,     0.99305,     0.99305,     0.99304,     0.99303,     0.99302,       0.993,       0.993,     0.99298,     0.99295,     0.99292,      0.9929,      0.9929,     0.99289,
            0.99289,     0.99289,     0.99288,     0.99284,     0.99281,     0.99279,     0.99279,     0.99278,     0.99278,     0.99278,     0.99278,     0.99276,     0.99272,     0.99272,      0.9927,      0.9927,     0.99268,     0.99266,     0.99264,     0.99263,     0.99263,     0.99263,     0.99263,
            0.99263,     0.99263,     0.99262,      0.9926,     0.99256,     0.99255,      0.9925,     0.99245,     0.99245,     0.99244,     0.99244,     0.99243,      0.9924,     0.99238,     0.99232,     0.99232,     0.99232,     0.99232,      0.9923,     0.99228,     0.99225,     0.99224,     0.99219,
            0.99219,     0.99218,     0.99215,     0.99213,      0.9921,     0.99209,     0.99208,     0.99208,     0.99206,     0.99206,     0.99206,     0.99204,     0.99199,     0.99195,     0.99193,     0.99193,      0.9919,     0.99188,     0.99187,     0.99184,     0.99184,     0.99183,     0.99183,
            0.99178,     0.99177,     0.99177,     0.99177,     0.99173,     0.99173,      0.9917,     0.99168,     0.99167,     0.99167,     0.99164,     0.99162,      0.9916,     0.99158,     0.99154,      0.9915,     0.99149,     0.99149,     0.99149,     0.99147,     0.99145,     0.99142,     0.99139,
            0.99137,     0.99136,     0.99134,      0.9913,     0.99129,     0.99127,     0.99125,     0.99123,     0.99121,     0.99115,     0.99114,     0.99114,     0.99113,     0.99111,     0.99108,     0.99108,     0.99108,     0.99103,     0.99102,     0.99102,     0.99102,     0.99099,     0.99095,
            0.99092,     0.99086,     0.99084,     0.99082,     0.99079,     0.99079,     0.99078,     0.99073,     0.99071,     0.99069,     0.99063,      0.9906,     0.99057,     0.99053,     0.99052,     0.99049,     0.99047,     0.99043,     0.99043,     0.99042,     0.99038,     0.99036,     0.99034,
            0.99033,     0.99033,     0.99031,     0.99028,     0.99024,     0.99022,     0.99019,     0.99019,     0.99016,     0.99016,     0.99015,     0.99014,     0.99013,     0.99013,     0.99011,     0.99009,     0.99004,        0.99,     0.98998,     0.98998,     0.98998,     0.98998,     0.98995,
            0.98994,     0.98989,     0.98986,     0.98986,     0.98983,     0.98979,     0.98977,     0.98976,     0.98973,     0.98968,     0.98965,     0.98961,     0.98958,     0.98957,     0.98957,     0.98956,     0.98953,     0.98953,     0.98948,     0.98942,     0.98941,      0.9894,     0.98935,
            0.98929,     0.98925,     0.98923,     0.98923,     0.98919,     0.98917,     0.98914,      0.9891,     0.98906,     0.98903,     0.98901,     0.98898,     0.98892,      0.9889,     0.98889,     0.98883,     0.98883,      0.9888,     0.98879,     0.98874,      0.9887,     0.98867,     0.98864,

model1: CNN model yolov8n
- mAP50: 0.8616581421565467
- mAP50-95: 0.5015154062809791
- Precision: 0.884327975980111
- Recall: 0.8033350408767347

In [ ]:
metrics1 = model1.val(split="test")  

print("mAP50:", metrics1.box.map50)
print("mAP50-95:", metrics1.box.map)
print("Precision:", metrics1.box.p.mean())
print("Recall:", metrics1.box.r.mean())

Ultralytics 8.4.37  Python-3.11.9 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 8188MiB)
val: Fast image access  (ping: 0.10.0 ms, read: 976.1585.0 MB/s, size: 1180.3 KB)
val: Scanning C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels.cache... 2935 images, 0 backgrounds, 1 corrupt: 100% ━━━━━━━━━━━━ 2936/2936  0.0s
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_274.jpg: ignoring corrupt image/label: image file is truncated (14 bytes not processed)
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 184/184 2.9it/s 1:030.3sss
                   all       2935     431419      0.884      0.803      0.862      0.502
Speed: 1.1ms preprocess, 5.0ms inference, 0.0ms loss, 2.5ms postprocess per image
Results saved to C:\Users\krist\runs\detect\val4
mAP50: 0.8616581421565467
mAP50-95: 0.5015154062809791
Precision: 0.884327975980111
Recall: 0.8033350408767347

model2: hybrid model (CNN+Transformer) yolo11s
- mAP50: 0.8905287384861946
- mAP50-95: 0.5373827766500494
- Precision: 0.9040873758344479
- Recall: 0.8358625837063273


--> Model scoort beter op alles dan model1

In [ ]:
metrics2 = model2.val(split="test")  

print("mAP50:", metrics2.box.map50)
print("mAP50-95:", metrics2.box.map)
print("Precision:", metrics2.box.p.mean())
print("Recall:", metrics2.box.r.mean())

# dit werd eigenlijk al meegegeven bij het trainen van het model

In [ ]:
# Test on new images
results1 = model1.predict(source='path-unseen-pictures', save=True)
results2 = model2.predict(source='path-unseen-pictures', save=True)

In [ ]:
predictor = OwlPredictor()

image_cv = cv2.imread(r"C:\Users\krist\Downloads\testimage.webp")

image = Image.fromarray(cv2.cvtColor(image_cv, cv2.COLOR_BGR2RGB))

texts = [["can", "soda can", "aluminium can", "soft drink can"]]

text_encodings = predictor.encode_text(texts)

predictions = predictor.predict(
    image=image,
    text_encodings=text_encodings,
    text=texts
)

boxes = predictions.boxes
scores = predictions.scores
labels = predictions.labels

Loading weights: 100%|██████████| 412/412 [00:00<00:00, 4985.48it/s]

In [22]:
boxes, scores, labels

(tensor([[131.0309,  22.6032, 370.4557, 465.1947]], device='cuda:0',
        grad_fn=<IndexBackward0>),
 tensor([0.2274], device='cuda:0', grad_fn=<IndexBackward0>),
 tensor([3], device='cuda:0'))

Test van Florence-2 op foto van winkelschappen

In [12]:
flash_attn = types.ModuleType("flash_attn")
flash_attn.__spec__ = importlib.machinery.ModuleSpec("flash_attn", None)

flash_attn_interface = types.ModuleType("flash_attn.flash_attn_interface")
flash_attn_interface.__spec__ = importlib.machinery.ModuleSpec("flash_attn.flash_attn_interface", None)

sys.modules["flash_attn"] = flash_attn
sys.modules["flash_attn.flash_attn_interface"] = flash_attn_interface

os.environ["FLASH_ATTENTION_FORCE_DISABLED"] = "1"

model_id = "microsoft/Florence-2-base"

processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

model3 = AutoModelForCausalLM.from_pretrained(
    model_id,
    trust_remote_code=True,
    attn_implementation="eager"
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model3 = model3.to(device)

image = Image.open(r"C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_0.jpg").convert("RGB")

task = "<DETAILED_CAPTION>"

inputs = processor(text=task, images=image, return_tensors="pt").to(device)

generated_ids = model3.generate(**inputs, max_new_tokens=100)
result = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(result)

The image shows a grocery store filled with lots of different types of food, including bottles, packets, and other objects arranged in racks. The floor is visible at the bottom of the image.

Generieke omschrijving van de winkelschappen maar dit is niet wat we zoeken. We gaan waarschijnlijk de bounding boxes van YOLOv11 apart moetten doorgeven per product naar Florence-2 zodat die voor elk product kan herkennen. Hiervoor testen we dit alvast op een apart product onder ideale omstandigheden.

In [2]:
flash_attn = types.ModuleType("flash_attn")
flash_attn.__spec__ = importlib.machinery.ModuleSpec("flash_attn", None)

flash_attn_interface = types.ModuleType("flash_attn.flash_attn_interface")
flash_attn_interface.__spec__ = importlib.machinery.ModuleSpec("flash_attn.flash_attn_interface", None)

sys.modules["flash_attn"] = flash_attn
sys.modules["flash_attn.flash_attn_interface"] = flash_attn_interface

os.environ["FLASH_ATTENTION_FORCE_DISABLED"] = "1"

model_id = "microsoft/Florence-2-base"

processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

model3 = AutoModelForCausalLM.from_pretrained(
    model_id,
    trust_remote_code=True,
    attn_implementation="eager"
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model3 = model3.to(device)

image = Image.open(r"C:\Users\krist\Downloads\testimage.webp").convert("RGB")

task = "<DETAILED_CAPTION>"

inputs = processor(text=task, images=image, return_tensors="pt").to(device)

generated_ids = model3.generate(**inputs, max_new_tokens=100)
result = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(result)

The image shows a 330ml can of Fanta Zero Sugar Orange, with a bright orange color and the words "Fanta" written in bold white font.

De omschtijving is zeer uitgebreid en omschrijft het product genoeg om het als uniek product op te zoeken (niet generiek zoals "blikje frisdrank"). Herkent ook dat dit de zero variant is wat zeer goed is voor onze toepassing. Er is echter nog een andere mode "OCR" die het product kan lezen. Dit kan misschien meer informatie van het blikje lezen voor sterk gelijkende producten beter te onderscheiden.

In [7]:
flash_attn = types.ModuleType("flash_attn")
flash_attn.__spec__ = importlib.machinery.ModuleSpec("flash_attn", None)

flash_attn_interface = types.ModuleType("flash_attn.flash_attn_interface")
flash_attn_interface.__spec__ = importlib.machinery.ModuleSpec("flash_attn.flash_attn_interface", None)

sys.modules["flash_attn"] = flash_attn
sys.modules["flash_attn.flash_attn_interface"] = flash_attn_interface

os.environ["FLASH_ATTENTION_FORCE_DISABLED"] = "1"

model_id = "microsoft/Florence-2-base"

processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

model3 = AutoModelForCausalLM.from_pretrained(
    model_id,
    trust_remote_code=True,
    attn_implementation="eager"
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model3 = model3.to(device)

image = Image.open(r"C:\Users\krist\Downloads\testimage.webp").convert("RGB")

task = "<OCR>"

inputs = processor(text=task, images=image, return_tensors="pt").to(device)

generated_ids = model3.generate(**inputs, max_new_tokens=100)
result = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(result)

FANTAZero sugarorange

Dit bleek toch niet een verbetering te zijn tegenover de vorige test, we zullen ons dus focussen op Detailed Caption bij de pipeline.

In [2]:
flash_attn = types.ModuleType("flash_attn")
flash_attn.__spec__ = importlib.machinery.ModuleSpec("flash_attn", None)

flash_attn_interface = types.ModuleType("flash_attn.flash_attn_interface")
flash_attn_interface.__spec__ = importlib.machinery.ModuleSpec("flash_attn.flash_attn_interface", None)

sys.modules["flash_attn"] = flash_attn
sys.modules["flash_attn.flash_attn_interface"] = flash_attn_interface

os.environ["FLASH_ATTENTION_FORCE_DISABLED"] = "1"

model_id = "microsoft/Florence-2-base"

processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

model3 = AutoModelForCausalLM.from_pretrained(
    model_id,
    trust_remote_code=True,
    attn_implementation="eager"
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model3 = model3.to(device)

image = Image.open(r"C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_0.jpg").convert("RGB")

task = "<OD>"

inputs = processor(text=task, images=image, return_tensors="pt").to(device)

generated_ids = model3.generate(**inputs, max_new_tokens=100)
result = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(result)

convenience store

In [3]:
flash_attn = types.ModuleType("flash_attn")
flash_attn.__spec__ = importlib.machinery.ModuleSpec("flash_attn", None)

flash_attn_interface = types.ModuleType("flash_attn.flash_attn_interface")
flash_attn_interface.__spec__ = importlib.machinery.ModuleSpec("flash_attn.flash_attn_interface", None)

sys.modules["flash_attn"] = flash_attn
sys.modules["flash_attn.flash_attn_interface"] = flash_attn_interface

os.environ["FLASH_ATTENTION_FORCE_DISABLED"] = "1"

model_id = "microsoft/Florence-2-base"

processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

model3 = AutoModelForCausalLM.from_pretrained(
    model_id,
    trust_remote_code=True,
    attn_implementation="eager"
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model3 = model3.to(device)

image = Image.open(r"C:\Users\krist\Downloads\testimage.webp").convert("RGB")

task = "<OD>"

inputs = processor(text=task, images=image, return_tensors="pt").to(device)

generated_ids = model3.generate(**inputs, max_new_tokens=100)
result = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(result)

orangetin can

Omdat FLorence-2 het product letterlijk beschrijft kan het interessant zijn voor producten die nieuw zijn en nog niet in bekende datasets terugkomen.

CLIP model zodat we de output kunnen meegeven met FAISS om dit te linken naar de producten. YOLO model geeft bounding boxes die gecropt worden en apart hiernaar doorgestuurd worden.

In [5]:
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

image = Image.open(r"C:\Users\krist\Downloads\testimage.webp").convert("RGB")

inputs = processor(images=image, return_tensors="pt").to(device)

with torch.no_grad():
    image_features = model.get_image_features(**inputs)

image_features = image_features / image_features.norm(dim=-1, keepdim=True)

print(image_features.shape) 
print(image_features[0][:10])

c:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\krist\.cache\huggingface\hub\models--openai--clip-vit-base-patch32. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

torch.Size([1, 512])
tensor([ 0.0164,  0.0038, -0.0083,  0.0537, -0.0041, -0.0073,  0.0146,  0.0316,  0.0091, -0.0124], device='cuda:0')

Dit geeft vector van de image die gebruikt kan worden door in andere datasets een gelijkaardig (hopelijk hetzelfde) product te vinden.

In [62]:
df_foodfacts = duckdb.query("""
    SELECT code, product_name[1].text AS clean_product_name, brands, images, countries_tags, ingredients_analysis_tags, nutriments
    FROM 'C:\\Users\\krist\\Documents\\Hogent_IT\\3de_jaar\\Bachelorproef\\bachproef26\\latex-hogent-bachproef\\bachproef\\datasets\\food.parquet'
    WHERE list_contains(countries_tags, 'en:belgium')
    AND brands IS NOT NULL
    AND images IS NOT NULL
    AND clean_product_name IS NOT NULL
    AND array_length(images) > 0
""").to_df()

print(df_foodfacts.columns)
print(len(df_foodfacts))

Index(['code', 'clean_product_name', 'brands', 'images', 'countries_tags',
       'ingredients_analysis_tags', 'nutriments'],
      dtype='str')
58834

In [63]:
display(df_foodfacts)

,code,clean_product_name,brands,images,countries_tags,ingredients_analysis_tags,nutriments
0,00011754,Cookies Stem Ginger,Marks & Spencer,"[{'key': '5', 'imgid': None, 'rev': None, 'siz...","[en:belgium, en:france, en:netherlands, en:uni...","[en:palm-oil-free, en:non-vegan, en:vegetarian]","[{'name': 'beta-carotene', 'value': None, '100..."
1,0011210006508,Tabasco Habanero Sauce,TABASCO,"[{'key': '13', 'imgid': None, 'rev': None, 'si...","[en:australia, en:belgium, en:france, en:germa...","[en:palm-oil-free, en:vegan, en:vegetarian]","[{'name': 'saturated-fat', 'value': None, '100..."
2,0011210115644,Tabasco Rojo,"McIlhenny Company,Tabasco","[{'key': '19', 'imgid': None, 'rev': None, 'si...","[en:belgium, en:spain]","[en:palm-oil-free, en:vegan, en:vegetarian]","[{'name': 'nova-group', 'value': None, '100g':..."
3,0011210600959,Tabasco Pepper Sauce,"McIlhenny Company, Tabasco","[{'key': '9', 'imgid': None, 'rev': None, 'siz...","[en:belgium, en:france]","[en:palm-oil-free, en:vegan, en:vegetarian]","[{'name': 'sucrose', 'value': None, '100g': 0...."
4,0011210601369,Tabasco Green Pepper Sauce,"Mc. Ilhenny Co., McIlhenny Company, Tabasco","[{'key': '2', 'imgid': None, 'rev': None, 'siz...","[en:belgium, en:france]","[en:palm-oil-free, en:vegan, en:vegetarian]","[{'name': 'fruits-vegetables-nuts', 'value': N..."
...,...,...,...,...,...,...,...
58829,5412952265201,Chocoladebloesem Puur,Dv Foods,"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",[en:belgium],<NA>,"[{'name': 'sodium', 'value': None, '100g': 9.9..."
58830,5400101256705,Fromage frais nature,Carrefour classic,"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",[en:belgium],<NA>,"[{'name': 'sodium', 'value': None, '100g': 0.2..."
58831,5410046700010,Compore bio,Materne,"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",[en:belgium],"[en:palm-oil-content-unknown, en:vegan-status-...","[{'name': 'fruits-vegetables-legumes', 'value'..."
58832,8720299907843,Dates,Medjoul,"[{'key': '1', 'imgid': None, 'rev': None, 'siz...",[en:belgium],<NA>,"[{'name': 'sugars', 'value': None, '100g': 68...."
58833,4056489542568,Jus de clémentine,Sol & Mar,"[{'key': '2', 'imgid': None, 'rev': None, 'siz...",[en:belgium],"[en:palm-oil-free, en:vegan, en:vegetarian]","[{'name': 'fiber', 'value': None, '100g': 0.10..."

probleem met Foodfacts database: de afbeeldingen gelinked aan de producten zijn soms niet dezelfde producten. Bij dit voorbeeld is key 4 en 5 een ander product... Inconsistencies zoals dit kan het model helemaal fout zetten. Er is dus weer eens echt nood op consistent en goed opgebouwde databases. Ook zijn vele foto's te veel ingezoomed zoals op de nutrition en ingredienten tabellen. Deze zijn bijna altijd hetzelfde (behalve de waarden) en zijn dus bijna onmogelijk deftig te linken, deze worden dus niet gebruikt.

We moetten dus zien of het model beter scoort op enkel front afbeeldingen of alle afbeeldingen meegenomen. Voor sommige producten zijn er afbeeldingen van alle kanten maar bij andere staan er foute producten bij. We moetten dus zien of dit de moeite is.

In [21]:
df_foodfacts["product_name"][4996]

array([{'lang': 'main', 'text': 'Carrefour Bon Appétit! Little Salad Penne au Thon'}, {'lang': 'fr', 'text': 'Carrefour Bon Appétit! Little Salad Penne au Thon'}], dtype=object)

In [22]:
df_foodfacts["images"][4996]

array([{'key': '1', 'imgid': None, 'rev': None, 'sizes': {'100': {'h': 94, 'w': 100}, '200': None, '400': {'h': 374, 'w': 400}, 'full': {'h': 1200, 'w': 1282}}, 'uploaded_t': 1532084700, 'uploader': 'kiliweb'},
       {'key': '3', 'imgid': None, 'rev': None, 'sizes': {'100': {'h': 89, 'w': 100}, '200': None, '400': {'h': 355, 'w': 400}, 'full': {'h': 1200, 'w': 1351}}, 'uploaded_t': 1532084706, 'uploader': 'kiliweb'},
       {'key': '2', 'imgid': None, 'rev': None, 'sizes': {'100': {'h': 53, 'w': 100}, '200': None, '400': {'h': 214, 'w': 400}, 'full': {'h': 1200, 'w': 2245}}, 'uploaded_t': 1532084703, 'uploader': 'kiliweb'},
       {'key': '4', 'imgid': None, 'rev': None, 'sizes': {'100': {'h': 72, 'w': 100}, '200': None, '400': {'h': 287, 'w': 400}, 'full': {'h': 614, 'w': 857}}, 'uploaded_t': 1597745625, 'uploader': 'kiliweb'},
       {'key': '5', 'imgid': None, 'rev': None, 'sizes': {'100': {'h': 100, 'w': 100}, '200': None, '400': {'h': 300, 'w': 300}, 'full': {'h': 300, 'w': 300}}, 'uploaded_t': 1721220487, 'uploader': 'org-carrefour-belgique'},
       {'key': 'nutrition_fr', 'imgid': 4, 'rev': 16, 'sizes': {'100': {'h': 72, 'w': 100}, '200': {'h': 143, 'w': 200}, '400': {'h': 287, 'w': 400}, 'full': {'h': 614, 'w': 857}}, 'uploaded_t': None, 'uploader': None},
       {'key': 'ingredients_fr', 'imgid': 2, 'rev': 9, 'sizes': {'100': {'h': 53, 'w': 100}, '200': {'h': 107, 'w': 200}, '400': {'h': 214, 'w': 400}, 'full': {'h': 1200, 'w': 2245}}, 'uploaded_t': None, 'uploader': None},
       {'key': 'front_fr', 'imgid': 5, 'rev': 26, 'sizes': {'100': {'h': 70, 'w': 100}, '200': {'h': 141, 'w': 200}, '400': {'h': 208, 'w': 296}, 'full': {'h': 208, 'w': 296}}, 'uploaded_t': None, 'uploader': None}], dtype=object)

Nu we weten hoe de database opgebouwd is kunnen we de juiste informatie eruit selecteren zodat we per row de correcte url maken die het product toont. Zo kan er gezocht worden naar hetzelfde product in de shelves

In [51]:
def build_image_url(code, key, rev, size="400"):
    code = str(code).zfill(13)

    prefix = code[:-4]
    suffix = code[-4:]

    parts = [prefix[i:i+3] for i in range(0, len(prefix), 3) if prefix[i:i+3]]
    parts.append(suffix)

    path = "/".join(parts)

    # Mogelijkheid 1: named images (front_fr.26.400.jpg)
    if rev is not None and not key.isdigit():
        url = f"https://images.openfoodfacts.org/images/products/{path}/{key}.{rev}.{size}.jpg"

    # Mogelijkheid 2: numeric images (5.400.jpg)
    if key.isdigit():
        url = f"https://images.openfoodfacts.org/images/products/{path}/{key}.{size}.jpg"
    
    print(url)
    return url

def get_front_image_url(images, code):
    if images is None:
        return None
    
    result = {}


    for img in images:
        key = img.get("key", "")
        rev = img.get("rev")  

        url = build_image_url(code, key, rev)

        if url is None:
            continue

        # store by key
        result[f"url_{key}"] = url

    return result

In [43]:
df_foodfacts["image_url"] = df_foodfacts.apply(get_front_image_url, axis=1)

df_foodfacts = df_foodfacts[df_foodfacts["image_url"].notna()]

https://images.openfoodfacts.org/images/products/000/000/001/1754/5.400.jpg
https://images.openfoodfacts.org/images/products/000/000/009/7857/front_nl.3.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/13.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/9.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/1369/2.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/011/3380/2.400.jpg
https://images.openfoodfacts.org/images/products/000/000/018/5400/2.400.jpg
https://images.openfoodfacts.org/images/products/002/017/689/0519/1.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/16.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/2.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/1.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/21.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/8.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/11.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/5528/24.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/7584/7.400.jpg
https://images.openfoodfacts.org/images/products/002/400/003/8269/4.400.jpg
https://images.openfoodfacts.org/images/products/002/400/010/0850/3.400.jpg
https://images.openfoodfacts.org/images/products/002/400/011/0170/6.400.jpg
https://images.openfoodfacts.org/images/products/002/400/012/4948/19.400.jpg
https://images.openfoodfacts.org/images/products/002/400/013/7139/20.400.jpg
https://images.openfoodfacts.org/images/products/002/400/014/6087/1.400.jpg
https://images.openfoodfacts.org/images/products/002/819/000/7944/5.400.jpg
https://images.openfoodfacts.org/images/products/003/120/045/6991/2.400.jpg
https://images.openfoodfacts.org/images/products/003/120/045/7004/2.400.jpg
https://images.openfoodfacts.org/images/products/003/120/045/7011/4.400.jpg
https://images.openfoodfacts.org/images/products/003/120/045/7035/2.400.jpg
https://images.openfoodfacts.org/images/products/003/400/023/9450/5.400.jpg
https://images.openfoodfacts.org/images/products/003/400/048/0128/6.400.jpg
https://images.openfoodfacts.org/images/products/003/400/060/0113/3.400.jpg
https://images.openfoodfacts.org/images/products/003/890/001/4278/6.400.jpg
https://images.openfoodfacts.org/images/products/003/890/002/9746/3.400.jpg
https://images.openfoodfacts.org/images/products/003/890/003/0414/2.400.jpg
https://images.openfoodfacts.org/images/products/003/890/009/2795/3.400.jpg
https://images.openfoodfacts.org/images/products/003/890/071/3546/3.400.jpg
https://images.openfoodfacts.org/images/products/003/904/701/0215/2.400.jpg
https://images.openfoodfacts.org/images/products/003/904/710/5720/7.400.jpg
https://images.openfoodfacts.org/images/products/003/904/710/5744/2.400.jpg
https://images.openfoodfacts.org/images/products/003/904/710/5782/2.400.jpg
https://images.openfoodfacts.org/images/products/003/904/710/5799/1.400.jpg
https://images.openfoodfacts.org/images/products/003/904/710/5874/1.400.jpg
https://images.openfoodfacts.org/images/products/003/904/714/6105/5.400.jpg
https://images.openfoodfacts.org/images/products/003/904/714/6495/8.400.jpg
https://images.openfoodfacts.org/images/products/003/904/714/6518/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/037/8611/1.400.jpg
https://images.openfoodfacts.org/images/products/004/600/028/3272/10.400.jpg
https://images.openfoodfacts.org/images/products/004/606/660/0068/3.400.jpg
https://images.openfoodfacts.org/images/products/000/000/041/6986/5.400.jpg
https://images.openfoodfacts.org/images/products/000/000/043/7622/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/046/9258/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/050/9077/2.400.jpg
https://images.openfoodfacts.org/images/products/006/410/010/8301/10.400.jpg
https://images.openfoodfacts.org/images/products/006/810/008/4238/20.400.jpg
https://images.openfoodfacts.org/images/products/006/820/091/0536/3.400.jpg
https://images.openfoodfacts.org/images/products/006/927/612/0034/3.400.jpg
https://images.openfoodfacts.org/images/products/007/017/701/0768/5.400.jpg
https://images.openfoodfacts.org/images/products/007/017/701/1710/1.400.jpg
https://images.openfoodfacts.org/images/products/007/017/704/2127/3.400.jpg
https://images.openfoodfacts.org/images/products/007/017/705/1174/2.400.jpg
https://images.openfoodfacts.org/images/products/007/017/705/2706/1.400.jpg
https://images.openfoodfacts.org/images/products/007/017/706/3597/ingredients.11.400.jpg
https://images.openfoodfacts.org/images/products/007/017/707/7198/3.400.jpg
https://images.openfoodfacts.org/images/products/007/017/708/7784/3.400.jpg
https://images.openfoodfacts.org/images/products/007/017/711/6088/1.400.jpg
https://images.openfoodfacts.org/images/products/007/017/711/8518/6.400.jpg
https://images.openfoodfacts.org/images/products/007/017/711/8563/2.400.jpg
https://images.openfoodfacts.org/images/products/007/017/714/5118/1.400.jpg
https://images.openfoodfacts.org/images/products/007/147/574/0012/7.400.jpg
https://images.openfoodfacts.org/images/products/007/156/799/0516/2.400.jpg
https://images.openfoodfacts.org/images/products/007/375/560/3888/13.400.jpg
https://images.openfoodfacts.org/images/products/007/460/101/1406/3.400.jpg
https://images.openfoodfacts.org/images/products/007/460/117/6167/5.400.jpg
https://images.openfoodfacts.org/images/products/007/549/600/1008/5.400.jpg
https://images.openfoodfacts.org/images/products/007/549/600/2005/4.400.jpg
https://images.openfoodfacts.org/images/products/007/684/060/0021/35.400.jpg
https://images.openfoodfacts.org/images/products/007/684/062/0036/5.400.jpg
https://images.openfoodfacts.org/images/products/000/000/070/2317/7.400.jpg
https://images.openfoodfacts.org/images/products/000/000/073/5346/10.400.jpg
https://images.openfoodfacts.org/images/products/000/000/074/1538/4.400.jpg
https://images.openfoodfacts.org/images/products/000/000/074/9145/2.400.jpg
https://images.openfoodfacts.org/images/products/008/000/000/0132/front_fr.8.400.jpg
https://images.openfoodfacts.org/images/products/008/136/436/1686/2.400.jpg
https://images.openfoodfacts.org/images/products/008/425/333/4129/7.400.jpg
https://images.openfoodfacts.org/images/products/008/490/900/1610/4.400.jpg
https://images.openfoodfacts.org/images/products/008/490/902/3049/5.400.jpg
https://images.openfoodfacts.org/images/products/008/766/605/2789/7.400.jpg
https://images.openfoodfacts.org/images/products/008/968/617/0108/12.400.jpg
https://images.openfoodfacts.org/images/products/008/968/617/0733/10.400.jpg
https://images.openfoodfacts.org/images/products/000/000/081/8919/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/083/5848/8.400.jpg
https://images.openfoodfacts.org/images/products/000/000/088/5584/4.400.jpg
https://images.openfoodfacts.org/images/products/000/000/089/5736/4.400.jpg
https://images.openfoodfacts.org/images/products/009/103/756/1428/3.400.jpg
https://images.openfoodfacts.org/images/products/009/103/756/1503/2.400.jpg
https://images.openfoodfacts.org/images/products/000/000/090/3851/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/091/1221/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/097/4110/4.400.jpg
https://images.openfoodfacts.org/images/products/012/345/678/9012/5.400.jpg
https://images.openfoodfacts.org/images/products/014/214/273/8073/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/000/000/166/5619/ingredients_es.20.400.jpg
https://images.openfoodfacts.org/images/products/020/554/300/9934/1.400.jpg
https://images.openfoodfacts.org/images/products/021/000/000/3738/2.400.jpg
https://images.openfoodfacts.org/images/products/022/142/021/5106/2.400.jpg
https://images.openfoodfacts.org/images/products/024/000/217/0763/nutrition_fr.5.400.jpg
https://images.openfoodfacts.org/images/products/029/821/803/7394/3.400.jpg
https://images.openfoodfacts.org/images/products/000/000/322/7139/2.400.jpg
https://images.openfoodfacts.org/images/products/000/000/326/6414/1.400.jpg
https://images.openfoodfacts.org/images/products/038/441/107/1812/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/041/111/711/0030/2.400.jpg
https://images.openfoodfacts.org/images/products/041/129/060/0014/ingredients.5.400.jpg
https://images.openfoodfacts.org/images/products/041/141/160/6475/front.3.400.jpg
https://images.openfoodfacts.org/images/products/000/000/415/7837/2.400.jpg
https://images.openfoodfacts.org/images/products/000/000/418/0098/front_nl.4.400.jpg
https://images.openfoodfacts.org/images/products/042/214/207/9339/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/046/821/009/1162/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/571/1772/1.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/0697/20.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/0710/24.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/0734/8.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/0758/6.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/0772/11.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/4527/17.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/4541/13.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/5012/7.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/6194/9.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/6224/9.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/9027/5.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/9058/10.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/9089/16.400.jpg
https://images.openfoodfacts.org/images/products/061/300/873/9119/2.400.jpg
https://images.openfoodfacts.org/images/products/061/928/660/3005/4.400.jpg
https://images.openfoodfacts.org/images/products/061/928/680/1005/4.400.jpg
https://images.openfoodfacts.org/images/products/063/779/300/0902/5.400.jpg
https://images.openfoodfacts.org/images/products/063/779/300/0957/8.400.jpg
https://images.openfoodfacts.org/images/products/063/779/300/1039/1.400.jpg
https://images.openfoodfacts.org/images/products/063/779/300/1053/13.400.jpg
https://images.openfoodfacts.org/images/products/063/779/303/3412/8.400.jpg
https://images.openfoodfacts.org/images/products/063/856/490/2562/1.400.jpg
https://images.openfoodfacts.org/images/products/064/052/214/9100/3.400.jpg
https://images.openfoodfacts.org/images/products/064/070/000/3224/2.400.jpg
https://images.openfoodfacts.org/images/products/064/343/124/7103/1.400.jpg
https://images.openfoodfacts.org/images/products/066/818/653/0799/1.400.jpg
https://images.openfoodfacts.org/images/products/072/822/912/3590/1.400.jpg
https://images.openfoodfacts.org/images/products/072/822/912/3811/6.400.jpg
https://images.openfoodfacts.org/images/products/072/822/912/4764/1.400.jpg
https://images.openfoodfacts.org/images/products/072/822/913/0444/5.400.jpg
https://images.openfoodfacts.org/images/products/073/402/797/2704/5.400.jpg
https://images.openfoodfacts.org/images/products/073/692/011/1310/11.400.jpg
https://images.openfoodfacts.org/images/products/073/692/011/1815/11.400.jpg
https://images.openfoodfacts.org/images/products/075/101/104/6913/10.400.jpg
https://images.openfoodfacts.org/images/products/076/211/114/1828/3.400.jpg
https://images.openfoodfacts.org/images/products/076/211/121/3709/2.400.jpg
https://images.openfoodfacts.org/images/products/076/257/150/0043/2.400.jpg
https://images.openfoodfacts.org/images/products/077/394/820/0008/9.400.jpg
https://images.openfoodfacts.org/images/products/078/522/112/3904/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/781/7221/3.400.jpg
https://images.openfoodfacts.org/images/products/000/000/802/1227/1.400.jpg
https://images.openfoodfacts.org/images/products/081/153/801/3062/15.400.jpg
https://images.openfoodfacts.org/images/products/081/738/001/0129/1.400.jpg
https://images.openfoodfacts.org/images/products/081/870/001/1017/2.400.jpg
https://images.openfoodfacts.org/images/products/083/611/000/2074/1.400.jpg
https://images.openfoodfacts.org/images/products/083/611/000/2609/2.400.jpg
https://images.openfoodfacts.org/images/products/083/732/800/0005/17.400.jpg
https://images.openfoodfacts.org/images/products/084/116/511/5587/2.400.jpg
https://images.openfoodfacts.org/images/products/084/665/600/6252/1.400.jpg
https://images.openfoodfacts.org/images/products/089/707/600/2010/5.400.jpg
https://images.openfoodfacts.org/images/products/089/899/900/0022/7.400.jpg
https://images.openfoodfacts.org/images/products/089/899/900/0503/34.400.jpg
https://images.openfoodfacts.org/images/products/089/899/900/7106/6.400.jpg
https://images.openfoodfacts.org/images/products/092/115/559/3455/front.3.400.jpg
https://images.openfoodfacts.org/images/products/097/886/910/1018/2.400.jpg
https://images.openfoodfacts.org/images/products/099/360/534/7529/1.400.jpg
https://images.openfoodfacts.org/images/products/100/295/158/0005/3.400.jpg
https://images.openfoodfacts.org/images/products/000/001/001/3833/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/000/001/001/8787/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/000/001/008/6988/5.400.jpg
https://images.openfoodfacts.org/images/products/000/001/012/3360/2.400.jpg
https://images.openfoodfacts.org/images/products/000/001/034/0335/1.400.jpg
https://images.openfoodfacts.org/images/products/110/308/626/0005/21.400.jpg
https://images.openfoodfacts.org/images/products/000/001/100/6078/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/101/9091/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/104/4204/19.400.jpg
https://images.openfoodfacts.org/images/products/000/001/104/7086/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/120/8887/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/121/6179/front_nl.4.400.jpg
https://images.openfoodfacts.org/images/products/000/001/122/3637/front.3.400.jpg
https://images.openfoodfacts.org/images/products/000/001/147/2797/1.400.jpg
https://images.openfoodfacts.org/images/products/120/028/890/0002/14.400.jpg
https://images.openfoodfacts.org/images/products/120/225/918/0000/1.400.jpg
https://images.openfoodfacts.org/images/products/121/803/363/8773/1.400.jpg
https://images.openfoodfacts.org/images/products/123/455/090/0049/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/254/8873/1.400.jpg
https://images.openfoodfacts.org/images/products/128/704/725/1001/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/311/0707/2.400.jpg
https://images.openfoodfacts.org/images/products/000/001/380/3803/9.400.jpg
https://images.openfoodfacts.org/images/products/000/001/400/1729/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/410/1885/12.400.jpg
https://images.openfoodfacts.org/images/products/000/001/412/1784/2.400.jpg
https://images.openfoodfacts.org/images/products/000/001/414/8187/1.400.jpg
https://images.openfoodfacts.org/images/products/142/004/390/2007/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/422/8687/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/533/9683/1.400.jpg
https://images.openfoodfacts.org/images/products/154/001/410/3/3943/4.400.jpg
https://images.openfoodfacts.org/images/products/154/001/410/5/7130/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/000/001/560/1216/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/160/374/893/0005/2.400.jpg
https://images.openfoodfacts.org/images/products/000/001/610/1007/13.400.jpg
https://images.openfoodfacts.org/images/products/000/001/681/1207/19.400.jpg
https://images.openfoodfacts.org/images/products/000/001/699/1927/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/704/3998/1.400.jpg
https://images.openfoodfacts.org/images/products/000/001/720/6008/5.400.jpg
https://images.openfoodfacts.org/images/products/000/001/723/7008/7.400.jpg
https://images.openfoodfacts.org/images/products/175/816/018/7770/2.400.jpg
https://images.openfoodfacts.org/images/products/000/001/760/0262/2.400.jpg
https://images.openfoodfacts.org/images/products/180/129/669/0000/7.400.jpg
https://images.openfoodfacts.org/images/products/000/001/810/3401/2.400.jpg
https://images.openfoodfacts.org/images/products/000/001/819/1998/2.400.jpg
https://images.openfoodfacts.org/images/products/190/308/627/0000/11.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/0031/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/2603/6.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/7884/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/7885/11.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/7886/9.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/7887/4.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/7888/2.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/7890/4.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/8245/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/8669/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/000/8762/9.400.jpg
https://images.openfoodfacts.org/images/products/200/000/001/0926/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/001/6221/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/001/6222/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0867/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0868/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0869/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0870/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0872/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0874/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0875/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0876/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0877/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0878/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0879/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0880/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0881/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0882/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0883/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/0888/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/2171/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/2852/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/3565/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/5569/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/5570/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/5571/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/5575/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/5576/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/5578/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/5579/1.400.jpg
https://images.openfoodfacts.org/images/products/200/000/002/5580/1.400.jpg

In [52]:
def expand_dataframe(df):
    url_columns = []

    for _, row in df.iterrows():
        urls = get_front_image_url(row["images"], row["code"])
        url_columns.append(urls)

    url_df = pd.DataFrame(url_columns)

    # merge original + new URL columns
    df_new = pd.concat([df.reset_index(drop=True), url_df], axis=1)

    return df_new

df_enriched = expand_dataframe(df_foodfacts)
display(df_enriched)

https://images.openfoodfacts.org/images/products/000/000/001/1754/5.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/3.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/2.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/4.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/nutrition_nl.29.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/nutrition_fr.21.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/ingredients_fr.14.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/ingredients_en.30.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/ingredients_nl.28.400.jpg
https://images.openfoodfacts.org/images/products/000/000/001/1754/front_fr.27.400.jpg
https://images.openfoodfacts.org/images/products/000/000/009/7857/front_nl.3.400.jpg
https://images.openfoodfacts.org/images/products/000/000/009/7857/1.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/13.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/15.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/2.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/14.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/8.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/18.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/4.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/3.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/12.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/7.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/9.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/11.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/6.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/19.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/5.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/17.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/10.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/1.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/16.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/front_de.78.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/front_en.61.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/front_fr.17.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/ingredients_nl.47.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/ingredients_en.39.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/ingredients_de.54.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/ingredients_fr.46.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/nutrition_fr.25.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/nutrition_en.75.400.jpg
https://images.openfoodfacts.org/images/products/001/121/000/6508/nutrition_de.55.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/9.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/7.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/1.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/10.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/6.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/5.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/3.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/8.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/4.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/2.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/front_fr.30.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/front_nl.34.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/ingredients_fr.31.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/0959/nutrition_fr.15.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/1369/2.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/1369/1.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/1369/nutrition_fr.21.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/1369/front_fr.8.400.jpg
https://images.openfoodfacts.org/images/products/001/121/060/1369/ingredients_fr.18.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/1.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/2.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/4.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/3.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/nutrition_fr.19.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/nutrition_en.6.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/front_en.4.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/front_fr.25.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/ingredients_en.5.400.jpg
https://images.openfoodfacts.org/images/products/001/254/631/5098/ingredients_fr.16.400.jpg
https://images.openfoodfacts.org/images/products/000/000/011/3380/2.400.jpg
https://images.openfoodfacts.org/images/products/000/000/011/3380/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/011/3380/nutrition_fr.7.400.jpg
https://images.openfoodfacts.org/images/products/000/000/011/3380/front_fr.5.400.jpg
https://images.openfoodfacts.org/images/products/000/000/011/3380/ingredients_fr.6.400.jpg
https://images.openfoodfacts.org/images/products/000/000/018/5400/2.400.jpg
https://images.openfoodfacts.org/images/products/000/000/018/5400/1.400.jpg
https://images.openfoodfacts.org/images/products/000/000/018/5400/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/000/000/018/5400/nutrition_fr.5.400.jpg
https://images.openfoodfacts.org/images/products/002/017/689/0519/1.400.jpg
https://images.openfoodfacts.org/images/products/002/017/689/0519/2.400.jpg
https://images.openfoodfacts.org/images/products/002/017/689/0519/3.400.jpg
https://images.openfoodfacts.org/images/products/002/017/689/0519/ingredients_fr.7.400.jpg
https://images.openfoodfacts.org/images/products/002/017/689/0519/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/16.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/1.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/5.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/21.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/19.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/20.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/12.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/3.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/13.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/23.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/22.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/10.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/17.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/11.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/6.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/9.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/7.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/4.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/8.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/18.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/14.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/2.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/15.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/ingredients_fr.61.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/ingredients_en.50.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/front_en.48.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/front_es.59.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/nutrition_en.52.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/0418/nutrition_fr.27.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/2.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/10.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/16.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/18.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/3.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/14.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/13.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/12.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/11.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/17.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/19.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/6.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/8.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/7.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/9.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/4.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/5.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/15.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/20.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/1.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/front_fr.41.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/front_it.77.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/front_es.89.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/front_en.61.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/nutrition_it.81.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/nutrition_fr.19.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/nutrition_es.30.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/nutrition_en.63.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/ingredients_it.79.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/ingredients_fr.45.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/1859/ingredients_es.6.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/1.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/3.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/7.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/6.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/4.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/2.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/5.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/ingredients_de.19.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/ingredients_fr.21.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/ingredients_nl.20.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/front_fr.3.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/front_en.26.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/front_nl.11.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/nutrition_en.28.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2313/packaging_en.18.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/21.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/22.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/4.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/19.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/25.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/13.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/14.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/10.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/2.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/26.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/3.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/17.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/6.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/16.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/5.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/20.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/1.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/8.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/18.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/23.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/24.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/9.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/11.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/15.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/12.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/7.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/nutrition_en.59.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/nutrition_es.43.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/nutrition_fr.26.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/ingredients_en.58.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/ingredients_fr.12.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/ingredients_es.42.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/front_en.73.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/front_fr.35.400.jpg
https://images.openfoodfacts.org/images/products/002/400/001/2559/packaging_en.60.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/8.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/1.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/2.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/4.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/5.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/6.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/7.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/ingredients_fr.22.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/ingredients_de.18.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/front_de.17.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/front_fr.30.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/nutrition_fr.32.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4385/nutrition_de.19.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/11.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/18.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/1.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/5.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/13.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/19.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/12.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/3.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/10.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/4.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/15.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/20.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/6.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/9.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/17.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/16.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/23.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/14.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/22.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/7.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/8.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/2.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/21.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/nutrition_fr.34.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/nutrition_fi.50.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/front_fr.41.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/front_fi.57.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/packaging_fi.48.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/ingredients_fr.26.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/4675/ingredients_fi.46.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/5528/24.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/5528/1.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/5528/16.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/5528/12.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/5528/8.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/5528/25.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/5528/9.400.jpg
https://images.openfoodfacts.org/images/products/002/400/002/5528/23.400.jpg

,code,product_name,brands,images,countries_tags,ingredients_analysis_tags,nutriments,image_url,url_5,url_3,...,url_nutrition_mk,url_other_hr,url_front_fa,url_nutrition_fa,url_nutrition_lb,url_packaging_sr,url_nutrition_no,url_packaging_ca,url_packaging_th,url_nutrition_lt
0,00011754,"[{'lang': 'main', 'text': 'Cookies Stem Ginger...",Marks & Spencer,"[{'key': '5', 'imgid': None, 'rev': None, 'siz...","[en:belgium, en:france, en:netherlands, en:uni...","[en:palm-oil-free, en:non-vegan, en:vegetarian]","[{'name': 'beta-carotene', 'value': None, '100...",https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00097857,[],Tamara,"[{'key': 'front_nl', 'imgid': 1, 'rev': 3, 'si...",[en:belgium],<NA>,<NA>,https://images.openfoodfacts.org/images/produc...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0011210006508,"[{'lang': 'main', 'text': 'Tabasco Habanero Sa...",TABASCO,"[{'key': '13', 'imgid': None, 'rev': None, 'si...","[en:australia, en:belgium, en:france, en:germa...","[en:palm-oil-free, en:vegan, en:vegetarian]","[{'name': 'saturated-fat', 'value': None, '100...",https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0011210600959,"[{'lang': 'main', 'text': 'Tabasco Pepper Sauc...","McIlhenny Company, Tabasco","[{'key': '9', 'imgid': None, 'rev': None, 'siz...","[en:belgium, en:france]","[en:palm-oil-free, en:vegan, en:vegetarian]","[{'name': 'sucrose', 'value': None, '100g': 0....",https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0011210601369,"[{'lang': 'main', 'text': 'Tabasco Green Peppe...","Mc. Ilhenny Co., McIlhenny Company, Tabasco","[{'key': '2', 'imgid': None, 'rev': None, 'siz...","[en:belgium, en:france]","[en:palm-oil-free, en:vegan, en:vegetarian]","[{'name': 'fruits-vegetables-nuts', 'value': N...",https://images.openfoodfacts.org/images/produc...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4695,5400101255432,"[{'lang': 'main', 'text': 'Carrefour Classic' ...","Carrefour, Stylesse/form +","[{'key': '8', 'imgid': None, 'rev': None, 'siz...","[en:belgium, en:france]","[en:palm-oil-free, en:non-vegan, en:vegetarian]","[{'name': 'magnesium', 'value': None, '100g': ...",https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4696,5400101255982,"[{'lang': 'main', 'text': 'Carrefour Bon Appét...",Carrefour,"[{'key': '1', 'imgid': None, 'rev': None, 'siz...","[en:belgium, en:france]","[en:palm-oil-free, en:non-vegan, en:non-vegeta...","[{'name': 'energy', 'value': None, '100g': 800...",https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4697,5400101256057,"[{'lang': 'main', 'text': 'Huile de sesame'}, ...","Carrefour, Carrefour Sélection","[{'key': '1', 'imgid': None, 'rev': None, 'siz...",[en:belgium],"[en:palm-oil-content-unknown, en:vegan-status-...","[{'name': 'sugars', 'value': None, '100g': 0.0...",https://images.openfoodfacts.org/images/produc...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4698,5400101256118,"[{'lang': 'main', 'text': 'Carrefour Classic' ...",Carrefour,"[{'key': '6', 'imgid': None, 'rev': None, 'siz...","[en:belgium, en:france]","[en:palm-oil-free, en:vegan-status-unknown, en...","[{'name': 'carbohydrates', 'value': None, '100...",https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4699,5400101256224,"[{'lang': 'main', 'text': 'Sauce Soja Classic'...",Carrefour,"[{'key': '3', 'imgid': None, 'rev': None, 'siz...",[en:belgium],"[en:palm-oil-free, en:vegan, en:vegetarian]","[{'name': 'water', 'value': None, '100g': 62.7...",https://images.openfoodfacts.org/images/produc...,NaN,https://images.openfoodfacts.org/images/produc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN